### ISSUE TITLE
[BUG] On click of `pages` displays 404 

### ISSUE THREAD

**Issue by shubhimainalli** [Pradumnasaraf/open-source-with-pradumna#54]
### Description

if I click on this pages its showing 404 check the link

### Screenshots

![image](https://user-images.githubusercontent.com/70970530/172062436-7bd35027-94cb-460d-84f9-b3d19a6beb0b.png)

**Comment by Pradumnasaraf** [comment]
Thank for opening the issue, @shubhimainalli

**Comment by unnikrishnan2002** [comment]
I believe that this issue can be solved easily if the we actually provide the whole URL instead of relative URL. Currently it is linked to the url `/pages` which only works if we are in the repo and doesn't work on the hosted website . So we can just change the link to full URL ie; `https://github.com/Pradumnasaraf/open-source-with-pradumna/tree/main/pages` then it will be redirected to this repo`s code base. What do you think @Pradumnasaraf ?

**Comment by unnikrishnan2002** [comment]
If this makes sense to you , I can just make the fix.

**Comment by Pradumnasaraf** [comment]
> If this makes sense to you , I can just make the fix.

Hey!, Unni I think we don't need anymore to hyperlink the `pages` because it was used in the old version of this repo.

Best thing is that we can simply highlight it with backticks and remove the hyperlink.

**Comment by unnikrishnan2002** [comment]
Okay sure. Can I proceed with that and make the change you suggested?
